import type { CreateLaunchDraft, DuelBoardEntry, Launch } from "@/lib/types";

export const sampleLaunchDraft: CreateLaunchDraft = {
  name: "Walrus Duel",
  symbol: "WDUEL",
  description: "A memecoin launch tuned for PvP volume wars and creator vault yield.",
  walrusBlobId: "bafywalruslogo123",
  deepbookPoolLabel: "WDUEL/SUI",
  deepbookQuoteSymbol: "SUI",
  virtualSui: 500,
  virtualToken: 50_000,
  basePrice: 1,
  priceStepBps: 500,
  graduationThreshold: 6_000,
  buyTaxBps: 150,
  sellTaxBps: 250,
  vaultShareBps: 7_000,
};

export const sampleLaunches: Launch[] = [
  {
    id: "0xcurve01",
    name: "Forge Flap",
    symbol: "FLAP",
    description: "Perpetual creator vault with curve-native momentum and duel eligibility.",
    walrusBlobId: "walrus-flap-logo",
    creator: "0x9a1c...7b23",
    marketCapSui: 2_940,
    raisedSui: 1_820,
    reserveSui: 1_455,
    currentPrice: 3.4,
    virtualSui: 600,
    virtualToken: 75_000,
    graduated: false,
    taxes: {
      buyBps: 100,
      sellBps: 250,
      vaultShareBps: 8_000,
      creatorVaultSui: 113.5,
    },
    holder: {
      balance: 124_500,
      lots: 2,
    },
    deepbook: {
      ready: false,
      poolLabel: "WDUEL/SUI",
      quoteSymbol: "SUI",
      migrationStatus: "curve",
    },
    migration: {
      assetModel: "object",
    },
    duel: {
      duelId: 12,
      opponentSymbol: "BLOB",
      yourSideVolume: 745,
      enemySideVolume: 612,
      endsInMinutes: 18,
    },
  },
  {
    id: "0xcurve02",
    name: "Blob Runner",
    symbol: "BLOB",
    description: "Walrus-first launch with aggressive buy pressure and vault-fed creator runway.",
    walrusBlobId: "walrus-blob-logo",
    creator: "0x6f4d...c118",
    marketCapSui: 4_180,
    raisedSui: 2_760,
    reserveSui: 2_207,
    currentPrice: 4.2,
    virtualSui: 800,
    virtualToken: 90_000,
    graduated: false,
    taxes: {
      buyBps: 200,
      sellBps: 300,
      vaultShareBps: 6_500,
      creatorVaultSui: 221.8,
    },
    holder: {
      balance: 0,
      lots: 0,
    },
    deepbook: {
      ready: false,
      poolLabel: "BLOB/USDC",
      quoteSymbol: "USDC",
      migrationStatus: "queued",
    },
    migration: {
      assetModel: "package_queued",
      packageId: "0xqueued_blob_package",
    },
  },
  {
    id: "0xcurve03",
    name: "Vault Beast",
    symbol: "BEAST",
    description: "Tax-heavy creator economy token optimized for long-tail vault revenue.",
    walrusBlobId: "walrus-beast-logo",
    creator: "0xa2cc...0e9f",
    marketCapSui: 6_420,
    raisedSui: 6_050,
    reserveSui: 3_910,
    currentPrice: 6.9,
    virtualSui: 1_200,
    virtualToken: 100_000,
    graduated: true,
    taxes: {
      buyBps: 50,
      sellBps: 150,
      vaultShareBps: 9_000,
      creatorVaultSui: 415.2,
    },
    holder: {
      balance: 18_500,
      lots: 1,
    },
    deepbook: {
      ready: true,
      poolLabel: "BEAST/SUI",
      quoteSymbol: "SUI",
      migrationStatus: "deepbook",
    },
    migration: {
      assetModel: "coin_live",
      packageId: "0xbeast_coin_package",
      balanceManagerId: "0xbeast_balance_manager",
    },
  },
];

export const sampleDuels: DuelBoardEntry[] = [
  {
    duelId: 12,
    tokenA: "FLAP",
    tokenB: "BLOB",
    volumeA: 745,
    volumeB: 612,
    endsInMinutes: 18,
  },
  {
    duelId: 13,
    tokenA: "BEAST",
    tokenB: "SQUID",
    volumeA: 981,
    volumeB: 1_104,
    endsInMinutes: 24,
  },
];
